/// Generated by AssetsRefGenerator on 2022/01/04
class Res {
  static const String Gilroy_Black = "assets/fonts/Gilroy-Black.ttf";
  static const String Gilroy_Bold = "assets/fonts/Gilroy-Bold.ttf";
  static const String Gilroy_Light = "assets/fonts/Gilroy-Light.ttf";
  static const String Gilroy_Thin = "assets/fonts/Gilroy-Thin.ttf";
  static const String Gilroy_UltraLight = "assets/fonts/Gilroy-UltraLight.ttf";
  static const String metamorphose_100px = "assets/images/metamorphose_100px.png";
}
